feed/urls.py
from django.urls import path
from feed.views import HomePageView 
from feed.views import PostDetailView
from feed.views import AddPostView

app_name='feed'

urlpatterns = [
    path('', HomePageView.as_view() , name='index'),
    path('detail/<int:pk>/', PostDetailView.as_view() , name='detail' ),
    path('post/', AddPostView.as_view() , name='post'),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path


from feed import urls as feed_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include(feed_urls,namespace='feed') )
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feed/models.py
from django.db import models
from sorl.thumbnail import ImageField

class Post(models.Model):
    text=models.CharField(max_length=150 , blank=False, null=False)
    img=models.ImageField()


    def __str__(self):
        return (self.text)

feed/forms.py
from django import forms

class PostForm(forms.Form):
    image=forms.FileField()
    title=forms.CharField(label="Description")
    

feed/views.py
# from django.shortcuts import render    / This is used for function based views /
from django.contrib import messages
from django.views.generic import TemplateView
from django.views.generic import DetailView
from django.views.generic import FormView

from feed.models import Post
from feed.forms import PostForm



class HomePageView(TemplateView):

    template_name='home.html'

    def get_context_data(self, **kwargs):
        context= super().get_context_data(**kwargs)
        context['post']= Post.objects.all().order_by('-id')
        return context

class PostDetailView(DetailView):
    template_name='detail.html'
    model=Post


class AddPostView(FormView):
    template_name = 'new_post.html'
    form_class=PostForm
    success_url ='/'

    def dispatch(self, request, *args, **kwargs):
        self.request = request
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        # print(form.cleaned_data['text'])  // to get the text entered in the text area field and printing in terminal

        # Create a post
         
        new_object =Post.objects.create (
        text=form.cleaned_data['title'],
        img=form.cleaned_data['image']
        )
        messages.add_message(self.request, messages.SUCCESS, "Your post was successful")
        return super().form_valid(form)
        

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
</head>
<body>
    {% if messages %}
        {% for message in messages %}
            <div class="bg-{% if message.tags %}{{message.tags}}{% else %} success {% endif %} bg-gradient text-center text-white py-2 ">
                {{message}}
            </div>
        {% endfor %}

    {% endif %}
    
    {% include "includes/navbar.html" %}
   

    

    <div class="container">
      {% block body %} default content{% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</body>
</html>

templates/detail.html
 {% extends 'base.html' %}

 {% block title %} Detail View {% endblock %}

 {% block body %}
 <!-- <div>
 <a href="{% url 'feed:index' %}" style="text-decoration: none;position: sticky;"> &larr; Go back</a>
 </div> -->

<div class="row">
    <div class="col col-md-10 offset-md-1 my-4">
        <h3 class="mt-2" style="text-align: center; ">{{post.text}} </h3>
        <img src="{{post.img.url}}" class="img-fluid rounded "  alt="#">
    </div>
</div>
 {% endblock %}

templates/home.html
{% extends "base.html" %}
{% load sorl_thumbnail %}

{% block title %} New homepage
{% endblock %}

{% block body %}

<!-- <div style="padding-bottom: 10px; text-align: center; font-size: larger; position: sticky ; top:0px; background-color: rgb(235, 235, 235);">
<a href="{% url  'feed:post'  %}" style="text-decoration: none;"> Create Post &rarr;</a>
<br>
</div> -->


<div class="row">
    {% for every_post in post %}
    
    
                            <!-- <a href="{% url 'feed:detail' every_post.id %}" style="display: inline-block; text-decoration: none; font-weight: bolder; color:black;">
                                <br>
                                {% thumbnail every_post.img "200x200" crop='center' as im %}
                                <img src="{{im.url}}" height="{{im.height}}" width="{{im.width}}">
                                {% endthumbnail %}    </a>  -->

        <div class="col-sm-6 col-md-5 col-lg-3">
            <div class="card my-4" >
                {% thumbnail every_post.img "200x200" crop='center' as im %}
                    <img src="{{im.url}}" class="card-img-top" alt="#">
                {% endthumbnail %}
                <div class="card-body">
                    <p class="card-text text-nowrap overflow-hidden text-truncate">{{every_post.text}}</p>
                    <a href="{% url 'feed:detail' every_post.id %}" class="btn btn-primary">View Full Image</a>
                </div>
            </div>
        </div>

        {% empty %}
        <div class="col-sm-6 offset-sm-3 text-center py-5 my-5">
            <h2 class="mb-3">Welcome!</h2>
            <h5 class="mb-4">Add your first image?</h5>
            <a href="{% url 'feed:post' %}" class="btn btn-success">Upload Image </a>
        </div>
    {% endfor %}
</div>

{% endblock %}

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">Post Book</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse " id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-link active" aria-current="page" href="{% url 'feed:index' %}">Home</a>
          <a class="nav-link" href="{% url 'feed:post' %}">Add New Post</a>     
                
        </div>
      </div>
    </div>
  </nav>

templates/new_post.html
{% extends "base.html" %}

{% block title %} Add post {% endblock %}

{% block body %}
            <!-- <div>
                <a href="{% url 'feed:index' %}" style="text-decoration: none;">Go to Home &nwArr;</a>
                <br>
            </div> -->


<form method="post" action="" enctype="multipart/form-data" class="my-5 py-5 col-sm-4 offset-sm-4 ps-5  ">
    <h2>Upload here!</h2>
 {% csrf_token %}
{{form.as_p}}
<div>
<button type="submit" class="btn btn-success"> Submit</button>
<button type="button" class="btn btn-secondary"> <a href="{% url 'feed:index' %}" style="text-decoration: none;color: whitesmoke; ">Cancel</a></button>
</div>
</form>
{% endblock %}